[env]
platform = atmelavr
framework = arduino

lib_deps =
    techiewaifu/mtw-tinyloopscheduler

[env:uno]
board = uno

[env:nanoatmega328]
board = nanoatmega328

[env:megaatmega2560]
board = megaatmega2560

[env:leonardo]
board = leonardo