// SPDX-License-Identifier: Apache-2.0
/*
  MTW TinyLoopScheduler — ISR Post Task

  Demonstrates:
    - scheduler initialization with tinyls::init();
    - deferred callback registration from a hardware interrupt;
    - use of tinyls::postISR() inside an ISR;
    - execution of the deferred callback in the main program context;
    - safe use of Serial outside the hardware ISR.

  Hardware:
    - any supported AVR Arduino board;
    - push button connected between digital pin 2 and GND;
    - USB connection to a computer for Serial Monitor.

  Serial Monitor:
    - baud rate: 9600.

  Behavior:
    - digital pin 2 is configured with the internal pull-up resistor;
    - the pin normally reads HIGH;
    - pressing the button connects the pin to GND and produces a FALLING edge;
    - the hardware ISR calls tinyls::postISR();
    - postISR() stores a deferred callback request;
    - the callback itself is not executed inside the hardware ISR;
    - tinyls::tick() later executes deferredButtonTask() in main context;
    - deferredButtonTask() increases the event counter and prints a message;
    - button debouncing is not implemented in this basic example;
    - because mechanical button contacts can bounce, one physical button
      press may generate several interrupts and several output messages.

  Expected output:

    MTW TinyLoopScheduler started
    Press the button connected between pin 2 and GND
    One press may produce several events because debounce is disabled
    Deferred button event #1
    Deferred button event #2
    Deferred button event #3

  Important:
    - postISR() is intended only for use inside a normal AVR hardware ISR;
    - do not call Serial.print(), delay(), millis(), or long application code
      directly from the ISR;
    - the ISR should complete as quickly as possible;
    - postISR() records the request, while the callback executes later from
      tinyls::tick() in the main program context;
    - hardware button contacts may bounce;
    - one physical press can therefore generate several FALLING edges,
      several deferred requests, and several messages in Serial Monitor;
    - this is expected behavior in this example and is not a scheduler error;
    - button debouncing is intentionally omitted to keep the example focused
      on tinyls::postISR().

  Power saving:
    - MTW TinyLoopScheduler may enter AVR SLEEP_MODE_IDLE when the current
      scheduler pass has no immediate work;
    - the external interrupt generated by the button wakes the processor;
    - the deferred ISR request is processed by a following scheduler pass;
    - SLEEP_MODE_IDLE is a lightweight idle state, not a deep-sleep mode.

*/

#include <Arduino.h>
#include <MTW_TinyLoopScheduler.h>

/*
  Button input pin.

  On Arduino Uno and Nano, digital pin 2 supports external interrupt INT0.
*/
static const uint8_t BUTTON_PIN = 2u;

/*
  Number of deferred button callbacks executed.

  This variable is modified only in the main program context, not inside
  the hardware ISR, so it does not need to be declared volatile.
*/
static uint32_t eventCount = 0u;

/*
  Deferred button callback.

  The hardware ISR does not execute this function directly.
  tinyls::tick() calls it later in the normal main program context.

  Serial output is allowed here because this function does not run inside
  the hardware interrupt handler.
*/
static void deferredButtonTask()
{
    /*
      Count the processed button event.
    */
    ++eventCount;

    /*
      Print the event number.
    */
    Serial.print(F("Deferred button event #"));
    Serial.println(eventCount);
}

/*
  Hardware interrupt service routine.

  Keep the ISR short. It only records a deferred callback request.

  postISR() does not execute deferredButtonTask() here. The scheduler stores
  the function pointer and invokes the callback later from tinyls::tick().
*/
static void buttonISR()
{
    tinyls::postISR(deferredButtonTask);
}

void setup()
{
    /*
      Initialize serial communication.

      Open Serial Monitor and select 9600 baud.
    */
    Serial.begin(9600);

    /*
      Configure the button input.

      INPUT_PULLUP keeps the input HIGH while the button is released.
      Pressing the button connects the pin to GND and changes it to LOW.
    */
    pinMode(BUTTON_PIN, INPUT_PULLUP);

    /*
      Initialize the scheduler before interrupts can post callback requests.
    */
    tinyls::init();

    /*
      Attach the hardware interrupt.

      FALLING triggers buttonISR() when the button input changes
      from HIGH to LOW.
    */
    attachInterrupt(
        digitalPinToInterrupt(BUTTON_PIN),
        buttonISR,
        FALLING
    );

    /*
      Print startup instructions once.
    */
    Serial.println(F("MTW TinyLoopScheduler started"));
    Serial.println(
        F("Press the button connected between pin 2 and GND")
    );
    Serial.println(
        F("One press may produce several events because debounce is disabled")
    );
}

void loop()
{
    /*
      Execute one complete scheduler pass.

      At the beginning of a scheduler pass, tick() drains deferred ISR
      requests and executes their callbacks in the main program context.

      tick() should be called continuously. Do not place delay() or other
      long blocking operations in loop().
    */
    tinyls::tick();
}